### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by tobychui**
Hi there,

I have updated the image file so it can support later version of ArozOS!
I am new to docker as well, so if it is all right I will refer this repo as the official docker file source. 

Thanks!

### CODE REVIEW

**Comment by SysAdmin74** [comment]
Hello tobychui,

Thanks for your work, I have tested out with my machine. it work pretty well, your recently version of ArozOS had inspired me with some extra with docker. If you have interest in docker version. This repo can be the first one to be test out. I could help in maintaining, I will be merging your pull request.
Thanks ^^

**Comment by tobychui** [comment]
@SysAdmin74 I guess you will also need to keep the ./system and ./web folder a persistent storage as well as shown in another [arozos docker](https://github.com/asdf3601a/arozos-docker) project. As this has already been merged, maybe could you help modify the compose file instead? (Sorry I am also new to docker, so I am not sure what will happen if this path is not kept persistent).

**Comment by SysAdmin74** [comment]
@tobychui, This two folder? Were those core system files or just config data, I have take a look at another project you have mentioned, they seen to be config data. I will test them out in both method, kept persistent and not kept persistent.
I will come back with update after testing.

**Comment by SysAdmin74** [comment]
Hi @tobychui,
I have restructure the docker code, after looking the project you mentioned earlier. Those three folder were added to persistent storage and some docker environment were added for supporting. Would like to test it ? Let me know if there is something else missing

**Comment by tobychui** [comment]
Hi @SysAdmin74 ,

So cool that you switch to use the pre-build binary instead 😂
As I don't personally use docker, I guess I will leave it to the ArozOS users to figure it out if it is working or not.

Btw, I have added this repo's link to ArozOS README. Thanks so much for your help maintaining this dockerfile!

**Pull request merged**
